// ===== Tarot Card Data =====

const SUITS = { WANDS: 'wands', CUPS: 'cups', SWORDS: 'swords', PENTACLES: 'pentacles' };
const ARANA = { MAJOR: 'major', MINOR: 'minor' };

const CARDS = [
  // ===== Major Arcana (0-21) =====
  { id:0, nameEn:'The Fool', nameZh:'愚者', arcana:'major', rank:0,
    keywordsEn:['Beginnings','Innocence','Spontaneity'], keywordsZh:['开始','纯真','自由'],
    upEn:'New beginnings, fresh starts, spontaneity, free spirit. The Fool beckons you to embrace the unknown and trust the journey ahead.', upZh:'新的开始、全新的起点、自发性、自由精神。愚者邀请你拥抱未知，相信前方的旅程。',
    revEn:'Holding back, fear of change, recklessness, risk-taking without thought.', revZh:'退缩不前、害怕改变、鲁莽行事、不顾后果的冒险。' },
  { id:1, nameEn:'The Magician', nameZh:'魔术师', arcana:'major', rank:1,
    keywordsEn:['Manifestation','Resourcefulness','Power'], keywordsZh:['显化','足智多谋','力量'],
    upEn:'You have all the tools you need. Focus your will and manifest your desires into reality.', upZh:'你已拥有所需的全部工具。集中意志，将你的愿望显化为现实。',
    revEn:'Untapped talents, manipulation, trickery, wasting potential.', revZh:'未开发的天赋、操纵、欺骗、浪费潜能。' },
  { id:2, nameEn:'The High Priestess', nameZh:'女祭司', arcana:'major', rank:2,
    keywordsEn:['Intuition','Mystery','Inner knowledge'], keywordsZh:['直觉','神秘','内在智慧'],
    upEn:'Trust your intuition. The answers you seek lie within, not in the external world.', upZh:'相信你的直觉。你寻求的答案在内在，而非外在世界。',
    revEn:'Secrets withheld, disconnection from intuition, withdrawal, silence.', revZh:'隐藏的秘密、与直觉脱节、退缩、沉默。' },
  { id:3, nameEn:'The Empress', nameZh:'女皇', arcana:'major', rank:3,
    keywordsEn:['Abundance','Nurturing','Motherhood'], keywordsZh:['丰盛','滋养','母性'],
    upEn:'Abundance, fertility, creativity, and nurturing energy surround you. Nature and beauty call.', upZh:'丰盛、多产、创造力和滋养的能量环绕着你。自然与美在呼唤。',
    revEn:'Creative block, dependence, smothering, emptiness, neglect of self-care.', revZh:'创作阻塞、依赖、过度保护、空虚、忽视自我照顾。' },
  { id:4, nameEn:'The Emperor', nameZh:'皇帝', arcana:'major', rank:4,
    keywordsEn:['Authority','Structure','Stability'], keywordsZh:['权威','结构','稳定'],
    upEn:'Structure, stability, authority, and protection. Establish order and take command.', upZh:'结构、稳定、权威和保护。建立秩序，掌握主导权。',
    revEn:'Domination, excessive control, rigidity, inflexibility, tyranny.', revZh:'支配、过度控制、僵化、缺乏灵活性、专制。' },
  { id:5, nameEn:'The Hierophant', nameZh:'教皇', arcana:'major', rank:5,
    keywordsEn:['Tradition','Conformity','Moral guidance'], keywordsZh:['传统','遵从','道德指引'],
    upEn:'Spiritual wisdom, tradition, conformity, and guidance from established institutions.', upZh:'灵性智慧、传统、遵从以及来自成熟体系的指引。',
    revEn:'Rebellion, unorthodoxy, new approaches, challenging the status quo.', revZh:'反叛、非正统、新方法、挑战现状。' },
  { id:6, nameEn:'The Lovers', nameZh:'恋人', arcana:'major', rank:6,
    keywordsEn:['Love','Harmony','Choices'], keywordsZh:['爱情','和谐','选择'],
    upEn:'Deep connections, harmony, love, and meaningful choices aligned with your values.', upZh:'深刻的联结、和谐、爱情以及符合你价值观的重要选择。',
    revEn:'Disharmony, imbalance, misalignment of values, broken communication.', revZh:'不和谐、失衡、价值观冲突、沟通破裂。' },
  { id:7, nameEn:'The Chariot', nameZh:'战车', arcana:'major', rank:7,
    keywordsEn:['Willpower','Determination','Victory'], keywordsZh:['意志力','决心','胜利'],
    upEn:'Determination, willpower, and victory through focused effort. Overcome obstacles through sheer drive.', upZh:'决心、意志力和以专注的努力取得胜利。用纯粹的驱动力克服障碍。',
    revEn:'Lack of direction, aggression, obstacles, loss of control, defeated.', revZh:'缺乏方向、侵略性、障碍、失控、挫败。' },
  { id:8, nameEn:'Strength', nameZh:'力量', arcana:'major', rank:8,
    keywordsEn:['Courage','Compassion','Inner strength'], keywordsZh:['勇气','慈悲','内在力量'],
    upEn:'Inner strength, courage, compassion, and gentle persuasion overcome brute force.', upZh:'内在力量、勇气、慈悲和温和的劝导胜过蛮力。',
    revEn:'Weakness, self-doubt, insecurity, low self-esteem, brute force.', revZh:'软弱、自我怀疑、不安、自卑、蛮力。' },
  { id:9, nameEn:'The Hermit', nameZh:'隐士', arcana:'major', rank:9,
    keywordsEn:['Soul-searching','Introspection','Solitude'], keywordsZh:['寻找自我','内省','独处'],
    upEn:'Solitude, introspection, soul-searching, and inner guidance. Seek wisdom within.', upZh:'独处、内省、寻找自我和内在指引。从内在寻求智慧。',
    revEn:'Isolation, loneliness, withdrawal, losing your way, being antisocial.', revZh:'孤立、孤独、退缩、迷失方向、不合群。' },
  { id:10, nameEn:'Wheel of Fortune', nameZh:'命运之轮', arcana:'major', rank:10,
    keywordsEn:['Change','Cycles','Destiny'], keywordsZh:['变化','循环','命运'],
    upEn:'Cycles of change, destiny, turning points, and the natural rhythm of life.', upZh:'变化的循环、命运、转折点以及生命的自然节律。',
    revEn:'Bad luck, resistance to change, broken cycles, out of alignment.', revZh:'厄运、抗拒变化、循环中断、失去平衡。' },
  { id:11, nameEn:'Justice', nameZh:'正义', arcana:'major', rank:11,
    keywordsEn:['Fairness','Truth','Law'], keywordsZh:['公正','真理','法律'],
    upEn:'Fairness, truth, justice, cause and effect, and accountability for actions.', upZh:'公正、真理、正义、因果以及为行为负责。',
    revEn:'Injustice, dishonesty, lack of accountability, imbalance, corruption.', revZh:'不公正、不诚实、不负责任、失衡、腐败。' },
  { id:12, nameEn:'The Hanged Man', nameZh:'倒吊人', arcana:'major', rank:12,
    keywordsEn:['Surrender','Perspective','Pause'], keywordsZh:['放下','新视角','暂停'],
    upEn:'Pause, surrender, letting go, seeing from a new perspective, suspension.', upZh:'暂停、放下、释怀、以新的视角看待问题、悬置。',
    revEn:'Stalling, resistance to change, stalling, martyrdom, unnecessary sacrifice.', revZh:'拖延、抗拒变化、停滞、殉道心态、不必要的牺牲。' },
  { id:13, nameEn:'Death', nameZh:'死神', arcana:'major', rank:13,
    keywordsEn:['Transformation','Endings','Change'], keywordsZh:['转变','结束','变化'],
    upEn:'Transformation, endings, change, transition, and letting go of what no longer serves.', upZh:'转变、结束、变化、过渡以及放下不再服务于你的事物。',
    revEn:'Resistance to change, stagnation, decay, repeating negative patterns.', revZh:'抗拒变化、停滞、衰退、重复负面模式。' },
  { id:14, nameEn:'Temperance', nameZh:'节制', arcana:'major', rank:14,
    keywordsEn:['Balance','Moderation','Harmony'], keywordsZh:['平衡','适度','和谐'],
    upEn:'Balance, moderation, patience, and finding harmony through the middle path.', upZh:'平衡、适度、耐心以及通过中庸之道找到和谐。',
    revEn:'Imbalance, excess, lack of patience, discord, extremes.', revZh:'失衡、过度、缺乏耐心、不和谐、极端。' },
  { id:15, nameEn:'The Devil', nameZh:'恶魔', arcana:'major', rank:15,
    keywordsEn:['Bondage','Materialism','Shadow self'], keywordsZh:['束缚','物质主义','阴影'],
    upEn:'Shadow self, materialism, bondage, addiction, and the things that hold you captive.', upZh:'阴影自我、物质主义、束缚、成瘾以及困住你的事物。',
    revEn:'Release, breaking free, reclaiming power, enlightenment, detachment.', revZh:'释放、挣脱、重获力量、觉醒、超脱。' },
  { id:16, nameEn:'The Tower', nameZh:'高塔', arcana:'major', rank:16,
    keywordsEn:['Upheaval','Sudden change','Revelation'], keywordsZh:['剧变','突然变化','启示'],
    upEn:'Sudden upheaval, chaos, revelation, awakening, and the collapse of false structures.', upZh:'突然的剧变、混乱、启示、觉醒以及虚假结构的崩塌。',
    revEn:'Disaster avoided, delaying the inevitable, resisting necessary change.', revZh:'避免灾难、推迟不可避免的事、抗拒必要的改变。' },
  { id:17, nameEn:'The Star', nameZh:'星星', arcana:'major', rank:17,
    keywordsEn:['Hope','Inspiration','Serenity'], keywordsZh:['希望','灵感','宁静'],
    upEn:'Hope, inspiration, serenity, renewal, healing, and spiritual guidance.', upZh:'希望、灵感、宁静、重生、疗愈和灵性指引。',
    revEn:'Hopelessness, despair, disconnection, lack of faith, discouragement.', revZh:'绝望、丧失信心、脱节、缺乏信念、气馁。' },
  { id:18, nameEn:'The Moon', nameZh:'月亮', arcana:'major', rank:18,
    keywordsEn:['Illusion','Fear','Subconscious'], keywordsZh:['幻象','恐惧','潜意识'],
    upEn:'Illusion, fear, anxiety, the subconscious, and things not being as they seem.', upZh:'幻象、恐惧、焦虑、潜意识以及事物并非表面所见。',
    revEn:'Release of fear, clarity, understanding, confusion lifting, repressed emotions surfacing.', revZh:'释放恐惧、清晰、理解、困惑消散、被压抑的情绪浮现。' },
  { id:19, nameEn:'The Sun', nameZh:'太阳', arcana:'major', rank:19,
    keywordsEn:['Joy','Success','Vitality'], keywordsZh:['喜悦','成功','活力'],
    upEn:'Success, joy, vitality, achievement, warmth, and the radiance of being alive.', upZh:'成功、喜悦、活力、成就、温暖以及生命的光辉。',
    revEn:'Temporary setbacks, lack of enthusiasm, sadness, difficulty seeing the bright side.', revZh:'暂时的挫折、缺乏热情、悲伤、难以看到光明面。' },
  { id:20, nameEn:'Judgement', nameZh:'审判', arcana:'major', rank:20,
    keywordsEn:['Judgement','Rebirth','Inner calling'], keywordsZh:['审判','重生','内在召唤'],
    upEn:'Judgement, rebirth, inner calling, absolution, and rising to a new level of being.', upZh:'审判、重生、内在召唤、赦免以及提升到新的存在层面。',
    revEn:'Self-doubt, ignoring inner calling, refusal to change, harsh self-criticism.', revZh:'自我怀疑、忽视内在召唤、拒绝改变、严苛的自我批评。' },
  { id:21, nameEn:'The World', nameZh:'世界', arcana:'major', rank:21,
    keywordsEn:['Completion','Wholeness','Achievement'], keywordsZh:['完成','圆满','成就'],
    upEn:'Completion, fulfillment, accomplishment, wholeness, and the end of a major cycle.', upZh:'完成、圆满、成就、完整以及一个重要周期的结束。',
    revEn:'Incompletion, delays, stagnation, seeking closure, shortcuts.', revZh:'未完成、延迟、停滞、寻求了结、走捷径。' },

  // ===== Wands (22-35) =====
  { id:22, nameEn:'Ace of Wands', nameZh:'权杖王牌', arcana:'minor', suit:'wands', rank:1,
    keywordsEn:['Inspiration','New potential','Creative spark'], keywordsZh:['灵感','新潜能','创作火花'],
    upEn:'New beginning, creative spark, inspiration, potential, and the seed of a great venture.', upZh:'新的开始、创作的灵感、启发、潜能以及伟大事业的种子。',
    revEn:'Lack of direction, delays, false starts, creative block, lack of passion.', revZh:'缺乏方向、延迟、开局不利、创作阻塞、缺乏激情。' },
  { id:23, nameEn:'Two of Wands', nameZh:'权杖二', arcana:'minor', suit:'wands', rank:2,
    keywordsEn:['Planning','Future vision','Decision'], keywordsZh:['规划','未来愿景','决策'],
    upEn:'Planning, future vision, making decisions, stepping out of your comfort zone.', upZh:'规划、展望未来、做决策、走出舒适区。',
    revEn:'Fear of change, lack of planning, poor decisions, playing small.', revZh:'害怕改变、缺乏规划、决策失误、安于现状。' },
  { id:24, nameEn:'Three of Wands', nameZh:'权杖三', arcana:'minor', suit:'wands', rank:3,
    keywordsEn:['Expansion','Foresight','Progress'], keywordsZh:['扩展','远见','进展'],
    upEn:'Progress, expansion, foresight, looking ahead, and preparing for what is to come.', upZh:'进展、扩展、远见、展望未来以及为即将到来之事做好准备。',
    revEn:'Delays, frustration, lack of progress, obstacles, setbacks.', revZh:'延迟、挫折、缺乏进展、阻碍、退步。' },
  { id:25, nameEn:'Four of Wands', nameZh:'权杖四', arcana:'minor', suit:'wands', rank:4,
    keywordsEn:['Celebration','Harmony','Homecoming'], keywordsZh:['庆祝','和谐','归家'],
    upEn:'Celebration, harmony, homecoming, joy, and the happiness of community.', upZh:'庆祝、和谐、归家、喜悦以及群体的欢乐。',
    revEn:'Lack of harmony, unstable foundation, cancelled celebrations, feeling unwelcome.', revZh:'缺乏和谐、基础不稳、庆祝取消、不受欢迎的感觉。' },
  { id:26, nameEn:'Five of Wands', nameZh:'权杖五', arcana:'minor', suit:'wands', rank:5,
    keywordsEn:['Competition','Conflict','Tension'], keywordsZh:['竞争','冲突','紧张'],
    upEn:'Competition, conflict, tension, rivalry, and the need to fight for your position.', upZh:'竞争、冲突、紧张、对抗以及为你的位置而战。',
    revEn:'Avoidance of conflict, inner conflict, finding common ground, peace restored.', revZh:'回避冲突、内心矛盾、找到共识、恢复和平。' },
  { id:27, nameEn:'Six of Wands', nameZh:'权杖六', arcana:'minor', suit:'wands', rank:6,
    keywordsEn:['Victory','Recognition','Praise'], keywordsZh:['胜利','认可','赞誉'],
    upEn:'Victory, public recognition, praise, progress, and confidence in success.', upZh:'胜利、公众认可、赞誉、进展以及对成功的信心。',
    revEn:'Lack of recognition, ego, failure, fall from grace, humility needed.', revZh:'缺乏认可、自负、失败、失宠、需要谦逊。' },
  { id:28, nameEn:'Seven of Wands', nameZh:'权杖七', arcana:'minor', suit:'wands', rank:7,
    keywordsEn:['Defence','Perseverance','Standing ground'], keywordsZh:['防守','坚持','坚守立场'],
    upEn:'Defence, perseverance, standing your ground, protecting your position, courage.', upZh:'防守、坚持、坚守立场、保卫你的位置、勇气。',
    revEn:'Overwhelmed, giving up, feeling defensive, being overwhelmed by opposition.', revZh:'不堪重负、放弃、防御过度、被对手压制。' },
  { id:29, nameEn:'Eight of Wands', nameZh:'权杖八', arcana:'minor', suit:'wands', rank:8,
    keywordsEn:['Speed','Action','Movement'], keywordsZh:['速度','行动','进展'],
    upEn:'Rapid progress, speed, action, movement, momentum, and things falling into place.', upZh:'快速进展、速度、行动、推进、势能以及事情步入正轨。',
    revEn:'Delays, slow pace, frustration, stagnation, loss of momentum.', revZh:'延迟、缓慢进展、挫折、停滞、失去势能。' },
  { id:30, nameEn:'Nine of Wands', nameZh:'权杖九', arcana:'minor', suit:'wands', rank:9,
    keywordsEn:['Resilience','Persistence','Boundaries'], keywordsZh:['韧性','坚持','边界'],
    upEn:'Resilience, persistence, last stand, boundaries, and the strength to keep going.', upZh:'韧性、坚持、最后一搏、边界以及继续前行的力量。',
    revEn:'Exhaustion, burnout, stubbornness, paranoia, giving up at the last hurdle.', revZh:'精疲力竭、倦怠、固执、多疑、在最后一关放弃。' },
  { id:31, nameEn:'Ten of Wands', nameZh:'权杖十', arcana:'minor', suit:'wands', rank:10,
    keywordsEn:['Burden','Responsibility','Hard work'], keywordsZh:['负担','责任','辛劳'],
    upEn:'Burden, responsibility, hard work, carrying too much, stress, and pressure.', upZh:'负担、责任、辛劳、承载过多、压力和紧张。',
    revEn:'Release of burden, delegation, sharing load, letting go of responsibilities.', revZh:'放下负担、委派、分担、放下责任。' },
  { id:32, nameEn:'Page of Wands', nameZh:'权杖侍从', arcana:'minor', suit:'wands', rank:11,
    keywordsEn:['Exploration','Enthusiasm','New ideas'], keywordsZh:['探索','热情','新想法'],
    upEn:'Exploration, enthusiasm, new ideas, creative potential, and free spirit.', upZh:'探索、热情、新想法、创作潜能和自由精神。',
    revEn:'Setbacks, lack of direction, procrastination, lack of passion, hasty decisions.', revZh:'挫折、缺乏方向、拖延、缺乏热情、草率决定。' },
  { id:33, nameEn:'Knight of Wands', nameZh:'权杖骑士', arcana:'minor', suit:'wands', rank:12,
    keywordsEn:['Passion','Adventure','Impulse'], keywordsZh:['激情','冒险','冲动'],
    upEn:'Passion, adventure, energy, impulsiveness, daring, and pursuing your vision.', upZh:'激情、冒险、能量、冲动、勇敢以及追寻你的愿景。',
    revEn:'Burnout, recklessness, lack of direction, delays, impulsive decisions.', revZh:'倦怠、鲁莽、缺乏方向、延迟、冲动的决定。' },
  { id:34, nameEn:'Queen of Wands', nameZh:'权杖王后', arcana:'minor', suit:'wands', rank:13,
    keywordsEn:['Confidence','Determination','Charisma'], keywordsZh:['自信','决心','魅力'],
    upEn:'Confidence, determination, charisma, warmth, and leading with passion.', upZh:'自信、决心、魅力、温暖以及以热情领导。',
    revEn:'Self-doubt, jealousy, selfishness, demanding, temperamental behavior.', revZh:'自我怀疑、嫉妒、自私、苛求、情绪化。' },
  { id:35, nameEn:'King of Wands', nameZh:'权杖国王', arcana:'minor', suit:'wands', rank:14,
    keywordsEn:['Vision','Leadership','Entrepreneurship'], keywordsZh:['远见','领导力','创业精神'],
    upEn:'Vision, leadership, entrepreneurship, boldness, and inspiring others to greatness.', upZh:'远见、领导力、创业精神、勇敢以及激励他人成就伟大。',
    revEn:'Ruthlessness, high expectations, temper, unrealistic goals, overbearing.', revZh:'冷酷、期望过高、暴躁、不切实际的目标、专横。' },

  // ===== Cups (36-49) =====
  { id:36, nameEn:'Ace of Cups', nameZh:'圣杯王牌', arcana:'minor', suit:'cups', rank:1,
    keywordsEn:['Love','New feelings','Compassion'], keywordsZh:['爱情','新感情','慈悲'],
    upEn:'New love, emotional awakening, compassion, openness, and the overflowing of feelings.', upZh:'新的爱情、情感觉醒、慈悲、开放以及满溢的情感。',
    revEn:'Emotional emptiness, blocked feelings, repressed emotions, withdrawal.', revZh:'情感空虚、情感阻塞、压抑情感、退缩。' },
  { id:37, nameEn:'Two of Cups', nameZh:'圣杯二', arcana:'minor', suit:'cups', rank:2,
    keywordsEn:['Connection','Partnership','Mutual attraction'], keywordsZh:['联结','伙伴关系','相互吸引'],
    upEn:'Connection, partnership, mutual attraction, unity, and the balance of giving and receiving.', upZh:'联结、伙伴关系、相互吸引、统一以及给予与接受的平衡。',
    revEn:'Imbalance in relationship, miscommunication, break-up, unequal partnership.', revZh:'关系失衡、沟通不畅、分手、不对等的伙伴关系。' },
  { id:38, nameEn:'Three of Cups', nameZh:'圣杯三', arcana:'minor', suit:'cups', rank:3,
    keywordsEn:['Friendship','Celebration','Community'], keywordsZh:['友谊','庆祝','社群'],
    upEn:'Friendship, celebration, joy, community, and the happiness of shared moments.', upZh:'友谊、庆祝、喜悦、社群以及共享时光的快乐。',
    revEn:'Overindulgence, gossip, social isolation, jealousy, cancelled plans.', revZh:'过度放纵、流言蜚语、社交孤立、嫉妒、取消的计划。' },
  { id:39, nameEn:'Four of Cups', nameZh:'圣杯四', arcana:'minor', suit:'cups', rank:4,
    keywordsEn:['Apathy','Contemplation','Discontent'], keywordsZh:['冷漠','沉思','不满'],
    upEn:'Apathy, contemplation, discontent, meditation, and the feeling of being uninspired.', upZh:'冷漠、沉思、不满、冥想以及缺乏灵感的感觉。',
    revEn:'New opportunities, awakening, renewed motivation, reaching out, acceptance.', revZh:'新机会、觉醒、重新燃起的动力、伸出援手、接受。' },
  { id:40, nameEn:'Five of Cups', nameZh:'圣杯五', arcana:'minor', suit:'cups', rank:5,
    keywordsEn:['Loss','Grief','Regret'], keywordsZh:['失落','悲伤','遗憾'],
    upEn:'Loss, grief, regret, disappointment, and focusing on what was lost rather than what remains.', upZh:'失落、悲伤、遗憾、失望以及专注于失去而非仍在的事物。',
    revEn:'Acceptance, moving on, finding peace, learning from loss, forgiveness.', revZh:'接受、继续前行、找到平静、从失去中学习、宽恕。' },
  { id:41, nameEn:'Six of Cups', nameZh:'圣杯六', arcana:'minor', suit:'cups', rank:6,
    keywordsEn:['Nostalgia','Childhood memories','Gifts'], keywordsZh:['怀旧','童年回忆','礼物'],
    upEn:'Nostalgia, happy memories, innocence, reunion, and the sweetness of the past.', upZh:'怀旧、美好回忆、纯真、重逢以及过去的甜蜜。',
    revEn:'Stuck in the past, unrealistic nostalgia, moving forward, leaving home.', revZh:'困在过去、不切实际的怀旧、向前迈进、离家。' },
  { id:42, nameEn:'Seven of Cups', nameZh:'圣杯七', arcana:'minor', suit:'cups', rank:7,
    keywordsEn:['Choices','Illusions','Fantasy'], keywordsZh:['选择','幻象','幻想'],
    upEn:'Choices, illusions, fantasy, wishful thinking, and the danger of too many options.', upZh:'选择、幻象、幻想、一厢情愿以及选项过多的困扰。',
    revEn:'Clarity, focus, realistic goals, narrowing down choices, commitment.', revZh:'清晰、专注、现实的目标、缩小选择、做出承诺。' },
  { id:43, nameEn:'Eight of Cups', nameZh:'圣杯八', arcana:'minor', suit:'cups', rank:8,
    keywordsEn:['Departure','Letting go','Moving on'], keywordsZh:['离开','放下','前行'],
    upEn:'Departure, walking away, letting go, seeking higher meaning, emotional growth.', upZh:'离开、转身离去、放下、追求更高意义、情感成长。',
    revEn:'Fear of letting go, aimless drifting, avoiding change, clinging to comfort.', revZh:'害怕放手、漫无目的、逃避改变、固守舒适区。' },
  { id:44, nameEn:'Nine of Cups', nameZh:'圣杯九', arcana:'minor', suit:'cups', rank:9,
    keywordsEn:['Contentment','Wishes granted','Satisfaction'], keywordsZh:['满足','愿望实现','满意'],
    upEn:'Contentment, wishes fulfilled, satisfaction, emotional fulfillment, and happiness.', upZh:'满足、愿望实现、满意、情感充实以及幸福。',
    revEn:'Lack of fulfillment, dissatisfaction, greed, materialism, unfulfilled wishes.', revZh:'不满足、不满、贪婪、物质主义、未实现的愿望。' },
  { id:45, nameEn:'Ten of Cups', nameZh:'圣杯十', arcana:'minor', suit:'cups', rank:10,
    keywordsEn:['Happiness','Family','Harmony'], keywordsZh:['幸福','家庭','和谐'],
    upEn:'Emotional fulfillment, family happiness, harmony, lasting joy, and peaceful relationships.', upZh:'情感满足、家庭幸福、和谐、持久的喜悦以及平静的关系。',
    revEn:'Broken family, disharmony, unrealistic ideals, domestic strife, shattered dreams.', revZh:'家庭破裂、不和谐、不切实际的理想、家庭冲突、梦想破碎。' },
  { id:46, nameEn:'Page of Cups', nameZh:'圣杯侍从', arcana:'minor', suit:'cups', rank:11,
    keywordsEn:['Creative inspiration','Intuition','Messenger'], keywordsZh:['创作灵感','直觉','信使'],
    upEn:'Creative inspiration, intuition, emotional messages, youthful enthusiasm, discovery.', upZh:'创作灵感、直觉、情感消息、年轻的热情、发现。',
    revEn:'Blocked creativity, emotional immaturity, insecurity, escapism, daydreaming.', revZh:'创作阻塞、情感不成熟、不安、逃避、白日梦。' },
  { id:47, nameEn:'Knight of Cups', nameZh:'圣杯骑士', arcana:'minor', suit:'cups', rank:12,
    keywordsEn:['Romance','Charm','Imagination'], keywordsZh:['浪漫','魅力','想象力'],
    upEn:'Romance, charm, imagination, following your heart, invitation, and beauty.', upZh:'浪漫、魅力、想象力、跟随内心、邀请以及美好。',
    revEn:'Jealousy, moodiness, unrealistic expectations, fantasy over reality, disappointment.', revZh:'嫉妒、情绪化、不切实际的期望、逃避现实、失望。' },
  { id:48, nameEn:'Queen of Cups', nameZh:'圣杯王后', arcana:'minor', suit:'cups', rank:13,
    keywordsEn:['Compassion','Emotional depth','Nurturing'], keywordsZh:['慈悲','情感深度','滋养'],
    upEn:'Compassion, emotional depth, nurturing, empathy, and caring for others with love.', upZh:'慈悲、情感深度、滋养、共情以及以关爱之心照顾他人。',
    revEn:'Emotional insecurity, co-dependence, martyrdom, smothering, emotional manipulation.', revZh:'情感不安、过度依赖、殉道心态、过度保护、情感操控。' },
  { id:49, nameEn:'King of Cups', nameZh:'圣杯国王', arcana:'minor', suit:'cups', rank:14,
    keywordsEn:['Emotional balance','Wisdom','Composure'], keywordsZh:['情感平衡','智慧','沉着'],
    upEn:'Emotional balance, wisdom, composure, diplomacy, and mature emotional management.', upZh:'情感平衡、智慧、沉着、外交手腕以及成熟的情感管理。',
    revEn:'Emotional volatility, moodiness, manipulation, erratic behavior, emotional repression.', revZh:'情绪波动、喜怒无常、操纵、反复无常的行为、情感压抑。' },

  // ===== Swords (50-63) =====
  { id:50, nameEn:'Ace of Swords', nameZh:'宝剑王牌', arcana:'minor', suit:'swords', rank:1,
    keywordsEn:['Clarity','Truth','Breakthrough'], keywordsZh:['清晰','真理','突破'],
    upEn:'Mental clarity, breakthrough, truth, new ideas, and the power of clear thinking.', upZh:'思维清晰、突破、真理、新想法以及清晰思考的力量。',
    revEn:'Confusion, misinformation, clouded judgement, lack of clarity, mental blocks.', revZh:'困惑、信息错误、判断模糊、缺乏清晰、思维阻塞。' },
  { id:51, nameEn:'Two of Swords', nameZh:'宝剑二', arcana:'minor', suit:'swords', rank:2,
    keywordsEn:['Difficult decision','Stalemate','Avoidance'], keywordsZh:['艰难抉择','僵局','回避'],
    upEn:'Difficult decision, stalemate, avoidance, denial, and being torn between two choices.', upZh:'艰难抉择、僵局、回避、否认以及在两难之间挣扎。',
    revEn:'Information revealed, facing reality, breaking the stalemate, making a decision.', revZh:'真相浮出、面对现实、打破僵局、做出决定。' },
  { id:52, nameEn:'Three of Swords', nameZh:'宝剑三', arcana:'minor', suit:'swords', rank:3,
    keywordsEn:['Heartbreak','Pain','Sorrow'], keywordsZh:['心碎','痛苦','悲伤'],
    upEn:'Heartbreak, pain, sorrow, grief, betrayal, and the sharp sting of emotional hurt.', upZh:'心碎、痛苦、悲伤、哀痛、背叛以及情感创伤的刺痛。',
    revEn:'Healing, release of pain, recovery, forgiveness, moving past grief.', revZh:'疗愈、释放痛苦、恢复、宽恕、走出悲伤。' },
  { id:53, nameEn:'Four of Swords', nameZh:'宝剑四', arcana:'minor', suit:'swords', rank:4,
    keywordsEn:['Rest','Recovery','Contemplation'], keywordsZh:['休息','恢复','沉思'],
    upEn:'Rest, recovery, contemplation, meditation, retreat, and the need for stillness.', upZh:'休息、恢复、沉思、冥想、退隐以及静下来的需要。',
    revEn:'Restlessness, burnout, impatience, pushing too hard, unable to rest.', revZh:'不安、倦怠、急躁、用力过猛、无法休息。' },
  { id:54, nameEn:'Five of Swords', nameZh:'宝剑五', arcana:'minor', suit:'swords', rank:5,
    keywordsEn:['Conflict','Defeat','Tension'], keywordsZh:['冲突','挫败','紧张'],
    upEn:'Conflict, tension, defeat, win-lose situations, and the lingering bitterness of arguments.', upZh:'冲突、紧张、挫败、输赢局面以及争论留下的苦涩。',
    revEn:'Reconciliation, moving on, compromise, letting go of ego, peace restored.', revZh:'和解、继续前行、妥协、放下自我、恢复和平。' },
  { id:55, nameEn:'Six of Swords', nameZh:'宝剑六', arcana:'minor', suit:'swords', rank:6,
    keywordsEn:['Transition','Moving on','Release'], keywordsZh:['过渡','前行','释放'],
    upEn:'Transition, moving on, release, leaving behind difficulty, journey toward peace.', upZh:'过渡、前行、释放、离开困境、走向平静。',
    revEn:'Resistance to change, baggage, unresolved issues, emotional turbulence, stuck.', revZh:'抗拒改变、包袱、未解决的问题、情绪动荡、卡住。' },
  { id:56, nameEn:'Seven of Swords', nameZh:'宝剑七', arcana:'minor', suit:'swords', rank:7,
    keywordsEn:['Deception','Strategy','Cunning'], keywordsZh:['欺骗','策略','狡猾'],
    upEn:'Deception, strategy, cunning, stealth, getting away with something, acting alone.', upZh:'欺骗、策略、狡猾、隐秘、瞒天过海、单独行动。',
    revEn:'Coming clean, confession, honesty, facing consequences, admitting wrongdoing.', revZh:'坦白、忏悔、诚实、面对后果、承认错误。' },
  { id:57, nameEn:'Eight of Swords', nameZh:'宝剑八', arcana:'minor', suit:'swords', rank:8,
    keywordsEn:['Restriction','Self-imposed limitation','Fear'], keywordsZh:['限制','自我设限','恐惧'],
    upEn:'Restriction, imprisonment, self-imposed limitations, negative thinking, feeling trapped.', upZh:'限制、禁锢、自我设限、消极思维、感觉被困住。',
    revEn:'Liberation, release from self-limiting beliefs, empowerment, new perspective, clarity.', revZh:'解放、摆脱自我设限的信念、赋权、新视角、清晰。' },
  { id:58, nameEn:'Nine of Swords', nameZh:'宝剑九', arcana:'minor', suit:'swords', rank:9,
    keywordsEn:['Anxiety','Worry','Nightmares'], keywordsZh:['焦虑','忧虑','噩梦'],
    upEn:'Anxiety, worry, fear, nightmares, overthinking, and sleepless nights of torment.', upZh:'焦虑、忧虑、恐惧、噩梦、过度思考以及不眠的折磨之夜。',
    revEn:'Release from worry, recovery, hope, overcoming anxiety, reaching out for help.', revZh:'摆脱忧虑、恢复、希望、克服焦虑、寻求帮助。' },
  { id:59, nameEn:'Ten of Swords', nameZh:'宝剑十', arcana:'minor', suit:'swords', rank:10,
    keywordsEn:['Rock bottom','End','Painful ending'], keywordsZh:['谷底','终结','痛苦结束'],
    upEn:'Rock bottom, painful ending, crisis, collapse, and the final blow.', upZh:'谷底、痛苦的结束、危机、崩塌以及最后的一击。',
    revEn:'Recovery, resurrection, lessons learned, healing, the end of a dark period.', revZh:'恢复、重生、吸取教训、疗愈、黑暗时期的结束。' },
  { id:60, nameEn:'Page of Swords', nameZh:'宝剑侍从', arcana:'minor', suit:'swords', rank:11,
    keywordsEn:['Curiosity','Ideas','Communication'], keywordsZh:['好奇心','想法','沟通'],
    upEn:'Curiosity, new ideas, communication, mental agility, and the thirst for knowledge.', upZh:'好奇心、新想法、沟通、思维敏捷以及对知识的渴求。',
    revEn:'Hasty words, overthinking, lack of direction, gossip, cynicism.', revZh:'轻率的言语、过度思考、缺乏方向、流言、愤世嫉俗。' },
  { id:61, nameEn:'Knight of Swords', nameZh:'宝剑骑士', arcana:'minor', suit:'swords', rank:12,
    keywordsEn:['Ambition','Drive','Action'], keywordsZh:['雄心','动力','行动'],
    upEn:'Ambition, drive, determination, action, focus, and charging toward your goals.', upZh:'雄心、动力、决心、行动、专注以及朝目标冲锋。',
    revEn:'Impulsiveness, scattered energy, lack of direction, overconfidence, burnout.', revZh:'冲动、精力分散、缺乏方向、过度自信、倦怠。' },
  { id:62, nameEn:'Queen of Swords', nameZh:'宝剑王后', arcana:'minor', suit:'swords', rank:13,
    keywordsEn:['Perception','Clear thinking','Boundaries'], keywordsZh:['洞察力','清晰思维','边界'],
    upEn:'Perception, clear thinking, boundaries, independence, and truth communicated with grace.', upZh:'洞察力、清晰思维、边界、独立以及以优雅传达真相。',
    revEn:'Cold-heartedness, bitterness, overly critical, harsh judgement, isolation.', revZh:'冷酷、怨恨、过于挑剔、严苛评判、孤立。' },
  { id:63, nameEn:'King of Swords', nameZh:'宝剑国王', arcana:'minor', suit:'swords', rank:14,
    keywordsEn:['Authority','Truth','Intellectual power'], keywordsZh:['权威','真理','智力'],
    upEn:'Authority, truth, intellectual power, discipline, fairness, and ethical leadership.', upZh:'权威、真理、智力、纪律、公正以及道德的领导者。',
    revEn:'Abuse of power, manipulation, coldness, tyranny, misuse of intellect.', revZh:'滥用权力、操纵、冷酷、专制、误用才智。' },

  // ===== Pentacles (64-77) =====
  { id:64, nameEn:'Ace of Pentacles', nameZh:'星币王牌', arcana:'minor', suit:'pentacles', rank:1,
    keywordsEn:['New opportunity','Prosperity','Abundance'], keywordsZh:['新机遇','繁荣','丰盛'],
    upEn:'New opportunity, prosperity, abundance, a fresh start in material or career matters.', upZh:'新机遇、繁荣、丰盛、物质或事业方面的新开始。',
    revEn:'Missed opportunity, lack of planning, poor investment, financial setbacks.', revZh:'错失机会、缺乏规划、投资失利、财务挫折。' },
  { id:65, nameEn:'Two of Pentacles', nameZh:'星币二', arcana:'minor', suit:'pentacles', rank:2,
    keywordsEn:['Balance','Adaptability','Juggling'], keywordsZh:['平衡','适应','兼顾'],
    upEn:'Balance, adaptability, juggling priorities, flexibility, and managing multiple responsibilities.', upZh:'平衡、适应、兼顾优先事项、灵活性以及管理多重责任。',
    revEn:'Overwhelm, imbalance, disorganization, dropped balls, financial strain.', revZh:'不堪重负、失衡、混乱、顾此失彼、财务紧张。' },
  { id:66, nameEn:'Three of Pentacles', nameZh:'星币三', arcana:'minor', suit:'pentacles', rank:3,
    keywordsEn:['Teamwork','Skill','Collaboration'], keywordsZh:['团队合作','技能','协作'],
    upEn:'Teamwork, collaboration, skill development, mastery, and working toward a common goal.', upZh:'团队合作、协作、技能发展、精通以及为共同目标努力。',
    revEn:'Lack of teamwork, skill issues, poor collaboration, apathy, disregard for quality.', revZh:'缺乏合作、技能不足、配合不佳、冷漠、忽视质量。' },
  { id:67, nameEn:'Four of Pentacles', nameZh:'星币四', arcana:'minor', suit:'pentacles', rank:4,
    keywordsEn:['Security','Control','Conservation'], keywordsZh:['安全','控制','保守'],
    upEn:'Security, control, conservation, saving resources, financial caution, holding on tight.', upZh:'安全、控制、保守、节省资源、财务谨慎、紧握不放。',
    revEn:'Greed, materialism, stinginess, financial insecurity, fear of loss, hoarding.', revZh:'贪婪、物质主义、吝啬、财务不安、害怕失去、囤积。' },
  { id:68, nameEn:'Five of Pentacles', nameZh:'星币五', arcana:'minor', suit:'pentacles', rank:5,
    keywordsEn:['Hardship','Poverty','Isolation'], keywordsZh:['困境','贫困','孤立'],
    upEn:'Hardship, poverty, isolation, feeling left out, financial loss, and difficult times.', upZh:'困境、贫困、孤立、被排斥感、财务损失以及艰难时期。',
    revEn:'Recovery from loss, finding support, spiritual wealth, turning a corner, renewal.', revZh:'从损失中恢复、找到支持、精神富足、转运、新生。' },
  { id:69, nameEn:'Six of Pentacles', nameZh:'星币六', arcana:'minor', suit:'pentacles', rank:6,
    keywordsEn:['Generosity','Charity','Sharing'], keywordsZh:['慷慨','慈善','分享'],
    upEn:'Generosity, charity, sharing, giving and receiving, gratitude, and balanced exchange.', upZh:'慷慨、慈善、分享、给予与接受、感恩以及平衡的交换。',
    revEn:'Strings attached, inequality, one-sided generosity, debt, unfairness.', revZh:'附带条件、不平等、单方面的慷慨、债务、不公。' },
  { id:70, nameEn:'Seven of Pentacles', nameZh:'星币七', arcana:'minor', suit:'pentacles', rank:7,
    keywordsEn:['Assessment','Patience','Long-term view'],
    upEn:'Assessment, patience, evaluation, reflection, reaping what you sow, long-term planning.', upZh:'评估、耐心、审视、反思、收获所种、长期规划。',
    revEn:'Delayed results, impatience, wasted effort, lack of growth, poor planning.', revZh:'成果延迟、不耐烦、白费力气、缺乏成长、规划不当。' },
  { id:71, nameEn:'Eight of Pentacles', nameZh:'星币八', arcana:'minor', suit:'pentacles', rank:8,
    keywordsEn:['Diligence','Craftsmanship','Skill development'], keywordsZh:['勤奋','匠心','技能提升'],
    upEn:'Diligence, craftsmanship, skill development, hard work, dedication, and mastery.', upZh:'勤奋、匠心、技能提升、努力工作、投入以及精通。',
    revEn:'Perfectionism, lack of motivation, shoddy work, cutting corners, lack of progress.', revZh:'完美主义、缺乏动力、粗制滥造、偷工减料、没有进展。' },
  { id:72, nameEn:'Nine of Pentacles', nameZh:'星币九', arcana:'minor', suit:'pentacles', rank:9,
    keywordsEn:['Luxury','Self-sufficiency','Indulgence'], keywordsZh:['奢华','自足','享受'],
    upEn:'Luxury, self-sufficiency, financial independence, refinement, and enjoying the good life.', upZh:'奢华、自足、财务独立、精致以及享受美好生活。',
    revEn:'Financial setback, superficiality, living beyond means, isolation, dependence.', revZh:'财务挫折、肤浅、超支、孤立、依赖。' },
  { id:73, nameEn:'Ten of Pentacles', nameZh:'星币十', arcana:'minor', suit:'pentacles', rank:10,
    keywordsEn:['Legacy','Wealth','Family inheritance'], keywordsZh:['传承','财富','家族继承'],
    upEn:'Legacy, wealth, family inheritance, long-term success, tradition, and lasting prosperity.', upZh:'传承、财富、家族继承、长期成功、传统以及持久的繁荣。',
    revEn:'Family loss, bankruptcy, disinheritance, financial failure, broken legacy.', revZh:'家族损失、破产、被剥夺继承权、财务失败、传承断裂。' },
  { id:74, nameEn:'Page of Pentacles', nameZh:'星币侍从', arcana:'minor', suit:'pentacles', rank:11,
    keywordsEn:['Ambition','Learning','Diligence'], keywordsZh:['志向','学习','勤奋'],
    upEn:'Ambition, learning, diligence, new skills, practical steps, and the start of a financial journey.', upZh:'志向、学习、勤奋、新技能、实际步骤以及财务旅程的开始。',
    revEn:'Lack of progress, laziness, missed opportunities, procrastination, poor planning.', revZh:'缺乏进展、懒惰、错失机会、拖延、规划不当。' },
  { id:75, nameEn:'Knight of Pentacles', nameZh:'星币骑士', arcana:'minor', suit:'pentacles', rank:12,
    keywordsEn:['Hard work','Responsibility','Methodical'], keywordsZh:['勤奋','责任','有条不紊'],
    upEn:'Hard work, responsibility, reliability, thoroughness, patience, and steady progress.', upZh:'勤奋、责任、可靠、细致、耐心以及稳步前进。',
    revEn:'Laziness, stagnation, stubbornness, boredom, lack of progress, complacency.', revZh:'懒惰、停滞、固执、无聊、缺乏进展、自满。' },
  { id:76, nameEn:'Queen of Pentacles', nameZh:'星币王后', arcana:'minor', suit:'pentacles', rank:13,
    keywordsEn:['Nurturing','Practicality','Abundance'], keywordsZh:['滋养','务实','丰盛'],
    upEn:'Nurturing, practicality, abundance, financial comfort, and creating a warm home.', upZh:'滋养、务实、丰盛、财务舒适以及营造温暖的家。',
    revEn:'Neglect, financial insecurity, smothering, workaholic, self-neglect, dependence.', revZh:'忽视、财务不安、过度保护、工作狂、自我忽视、依赖。' },
  { id:77, nameEn:'King of Pentacles', nameZh:'星币国王', arcana:'minor', suit:'pentacles', rank:14,
    keywordsEn:['Wealth','Leadership','Stability'], keywordsZh:['财富','领导力','稳定'],
    upEn:'Wealth, leadership, stability, abundance, success in business, and material mastery.', upZh:'财富、领导力、稳定、丰盛、商业成功以及物质掌握。',
    revEn:'Financial mismanagement, greed, stubbornness, excess, workaholism, material obsession.', revZh:'财务失当、贪婪、固执、过度、工作狂、物质迷恋。' },
];

// ===== Spread Definitions =====

const SPREADS = {
  'past-present-future': {
    key: 'past-present-future',
    nameEn: 'Past · Present · Future',
    nameZh: '过去 · 现在 · 未来',
    positions: [
      { index: 0, key: 'past', nameEn: 'Past', nameZh: '过去', descEn: 'The foundations that shaped you', descZh: '塑造你的基础与过往' },
      { index: 1, key: 'present', nameEn: 'Present', nameZh: '现在', descEn: 'Your current energy and situation', descZh: '你当下的能量与处境' },
      { index: 2, key: 'future', nameEn: 'Future', nameZh: '未来', descEn: 'What is approaching', descZh: '即将到来的可能' },
    ],
  },
  'body-mind-spirit': {
    key: 'body-mind-spirit',
    nameEn: 'Body · Mind · Spirit',
    nameZh: '身 · 心 · 灵',
    positions: [
      { index: 0, key: 'body', nameEn: 'Body', nameZh: '身体', descEn: 'Physical health and material realm', descZh: '身体健康与物质领域' },
      { index: 1, key: 'mind', nameEn: 'Mind', nameZh: '心灵', descEn: 'Emotions, thoughts, and relationships', descZh: '情感、思想与人际' },
      { index: 2, key: 'spirit', nameEn: 'Spirit', nameZh: '灵性', descEn: 'Higher self, purpose, and intuition', descZh: '更高自我与内在直觉' },
    ],
  },
};

// ===== Questions (placeholder - you provide these) =====

const QUESTIONS = [
  {
    id: 1,
    questionZh: '你目前最关注生活的哪个领域？',
    questionEn: 'Which area of life are you most focused on?',
    options: [
      { id: 'a', textZh: '事业与前途', textEn: 'Career & Future' },
      { id: 'b', textZh: '感情与关系', textEn: 'Love & Relationships' },
      { id: 'c', textZh: '自我与成长', textEn: 'Self & Growth' },
      { id: 'd', textZh: '家庭与生活', textEn: 'Family & Life' },
    ],
  },
  {
    id: 2,
    questionZh: '你当下的情绪状态更接近？',
    questionEn: 'What describes your current emotional state?',
    options: [
      { id: 'a', textZh: '期待与兴奋', textEn: 'Hopeful & Excited' },
      { id: 'b', textZh: '焦虑与不安', textEn: 'Anxious & Uneasy' },
      { id: 'c', textZh: '平静与满足', textEn: 'Calm & Content' },
      { id: 'd', textZh: '迷茫与困惑', textEn: 'Lost & Confused' },
    ],
  },
  {
    id: 3,
    questionZh: '你希望这次占卜为你带来什么？',
    questionEn: 'What do you hope to gain from this reading?',
    options: [
      { id: 'a', textZh: '明确的指引', textEn: 'Clear Guidance' },
      { id: 'b', textZh: '心灵的慰藉', textEn: 'Emotional Comfort' },
      { id: 'c', textZh: '全新的视角', textEn: 'A Fresh Perspective' },
      { id: 'd', textZh: '确认内心选择', textEn: 'Confirmation of a Choice' },
    ],
  },
  {
    id: 4,
    questionZh: '你近期正在面临的最大挑战是？',
    questionEn: 'What challenge are you currently facing?',
    options: [
      { id: 'a', textZh: '重要的人生决定', textEn: 'An Important Life Decision' },
      { id: 'b', textZh: '人际关系的处理', textEn: 'Navigating Relationships' },
      { id: 'c', textZh: '自我突破与改变', textEn: 'Personal Breakthrough & Change' },
      { id: 'd', textZh: '压力与情绪管理', textEn: 'Stress & Emotional Management' },
    ],
  },
  {
    id: 5,
    questionZh: '你的内心直觉在告诉你什么？',
    questionEn: 'What is your inner intuition telling you?',
    options: [
      { id: 'a', textZh: '是时候做出改变了', textEn: 'It\'s Time for a Change' },
      { id: 'b', textZh: '再坚持一下就会看到结果', textEn: 'Keep Going, Results Are Near' },
      { id: 'c', textZh: '需要停下来好好思考', textEn: 'Pause and Reflect' },
      { id: 'd', textZh: '相信自己的选择', textEn: 'Trust Your Own Choice' },
    ],
  },
];

